### ISSUE TITLE
something about function(sha1_finish) 

### ISSUE THREAD

**Issue by Longchuanzheng** [vyuh/hmac-sha1#2]
hellow,there is something puzzaled me in the function(sha1_finish) ,

...
  p = *msg;
  while (p.l[1] || (p.l[0] >= 512)) {
    sha1_nxt (p.d, 512, h);     /* FIXME check return value? */
    p.d += 64;
    if (p.l[0] < 512) {
      if (p.l[1]) {
        p.l[1]--;
      }
...
why you do: p.d += 64; in line 63
i think is already done in function(sha1_nxt)
can you help me understand these principe?
is it about the " pointer parameter in c function"?
thank you.

**Comment by vyuh** [comment]
Hi.

`sha1_nxt` does not change `p.d` it only changes a copy of it known as `msg`.
Pointer parameters are *passed-by-value* in C.
See https://stackoverflow.com/a/4426487/1921546 for some explanation.

Please tell if you get wrong result for some input.

All the best.
